# Generated by Django 2.2.2 on 2019-06-23 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('biography', models.TextField()),
                ('term', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_user', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=200)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
